FROM --platform=${BUILDPLATFORM} alpine:3.20.3 as alpine
RUN apk add -U --no-cache ca-certificates

# Image starts here
FROM scratch
ARG TARGETPLATFORM
LABEL maintainer "Lucas Lorentz <lucaslorentzlara@hotmail.com>"

EXPOSE 80 443 2019 8080
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

# Enable Host Status page by default for GHCR image
ENV CADDY_DOCKER_HOST_STATUS_URL=/caddy/hosts \
    CADDY_DOCKER_HOST_STATUS_TEMPLATE=/etc/caddy/hostview.html \
    CADDY_DOCKER_HOST_STATUS_ADDR=:8080

WORKDIR /

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# caddy binary from build artifacts
COPY artifacts/binaries/$TARGETPLATFORM/caddy /bin/

# bundled HostView template from artifacts (populated by build.sh)
COPY artifacts/hostview/hostview.html /etc/caddy/hostview.html

ENTRYPOINT ["/bin/caddy"]
CMD ["docker-proxy"]
